services:
  db:
    image: postgres:latest
    container_name: db
    ports:
      - "5433:5432"
    env_file:
      - .env
    volumes:
      - betting_house_volume:/var/lib/postgresql/data
    networks:
      - betting-house-network

  app:
    build: .
    container_name: betting-house-api-compose
    ports:
      - "80:5000"
    env_file:
      - .env
    networks:
      - betting-house-network
    depends_on:
      - db

networks:
  betting-house-network:
    name: betting-house-network
    driver: bridge

volumes:
  betting_house_volume: