services:
  db:
    image: postgres:latest
    container_name: db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
    volumes:
      - betting_house_volume:/var/lib/postgresql/data

  app:
    image: node:alpine
    container_name: betting-house-api-compose
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DATABASE}?schema=public
    command: 
      sh -c "npm install && npx prisma generate && npx prisma migrate deploy && npm start"
    depends_on:
      - db

volumes:
  betting_house_volume: